# Generated by Django 4.0.6 on 2022-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/comments/%Y/%m/%d', verbose_name='Фото Пользователя'),
        ),
    ]
