# Generated by Django 4.0.6 on 2022-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='photo/comments/%Y/%m/%d', verbose_name='Фото Пользователя'),
        ),
    ]
