# Generated by Django 4.0.6 on 2022-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inst',
            field=models.URLField(default='ins'),
        ),
    ]
