# Generated by Django 4.0.6 on 2022-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inst',
            field=models.URLField(blank=True, default='ins'),
        ),
    ]
